export default {
	FILE_SERVER: "http://localhost:5002",
	SEARCH_ENGINE: "http://127.0.0.1:7700",
	MONGO_URL: "--MONGO_URL--",
	GOOGLE_CLIENT_ID:
		"--GOOGLE_CLIENT_ID--",
	GOOGLE_CLIENT_SECRET: "--GOOGLE_CLIENT_SECRET--",
	GOOGLE_TOKEN_URL: "https://oauth2.googleapis.com/token",
	GOOGLE_USER_INFO_URL:
		"https://www.googleapis.com/oauth2/v3/userinfo?access_token=",
	GOOGLE_REDIRECT_URI: "http://localhost:3000/integration/google/callback",
	JWT_SECRET_KEY: "--JWT_SECRET_KEY--",
	RAZORPAY_KEY_ID: "--RAZORPAY_KEY_ID--",
	RAZORPAY_KEY_SECRET: "--RAZORPAY_KEY_SECRET--",
	RAZORPAY_WEBHOOK_SECRET: "--RAZORPAY_WEBHOOK_SECRET--",
	GOOGLE_CLIENT_ID_ANDROID: 
		"--GOOGLE_CLIENT_ID_ANDROID--",
	GOOGLE_CLIENT_SECRET_ANDROID: "--GOOGLE_CLIENT_SECRET_ANDROID--",
};
